-- Warehouse chargement S3 → Snowflake
CREATE WAREHOUSE IF NOT EXISTS LOADING_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Chargement données StreamVision depuis S3';

-- Warehouse transformations
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
WITH WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Transformations StreamVision';

-- Warehouse BI
CREATE WAREHOUSE IF NOT EXISTS BI_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 120
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'BI StreamVision';

SHOW WAREHOUSES;
